[08:36:52] INFO | three_chan.common.setup > Starting
[08:36:52] INFO | three_chan.common.setup > Started!
[08:36:57] INFO | root > Stopping app
[08:36:57] INFO | root > Stopped.
[08:38:00] INFO | three_chan.common.setup > Starting
[08:38:00] ERROR | three_chan.common.db > Failed to connect to database
Traceback (most recent call last):
  File "/3chan/three_chan/common/db.py", line 22, in initialize
    self._engine = create_async_engine(self._db_url)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/ext/asyncio/engine.py", line 120, in create_async_engine
    sync_engine = _create_engine(url, **kw)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 549, in create_engine
    u = _url.make_url(url)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/url.py", line 856, in make_url
    return _parse_url(name_or_url)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/url.py", line 922, in _parse_url
    raise exc.ArgumentError(
        "Could not parse SQLAlchemy URL from string '%s'" % name
    )
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from string 'dfcgvhjkhgf'
[08:38:47] INFO | three_chan.common.setup > Starting
[08:38:47] ERROR | three_chan.common.db > Failed to connect to database
Traceback (most recent call last):
  File "/3chan/three_chan/common/db.py", line 22, in initialize
    self._engine = create_async_engine(self._db_url)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/ext/asyncio/engine.py", line 120, in create_async_engine
    sync_engine = _create_engine(url, **kw)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 602, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 696, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[08:42:05] INFO | three_chan.common.setup > Starting
[08:42:05] INFO | three_chan.common.setup > Started!
[08:55:16] INFO | root > Stopping app
[08:55:16] INFO | root > Stopped.
[08:55:25] INFO | three_chan.common.setup > Starting
[08:55:25] INFO | three_chan.common.setup > Started!
[09:06:13] INFO | three_chan.common.setup > Starting
[09:06:13] INFO | three_chan.common.setup > Started!
[09:08:05] INFO | root > Stopping app
[09:08:05] INFO | root > Stopped.
